# usage:  
#   create: k3d cluster create --config k3d.yaml
#   delete: k3d cluster delete --config k3d.yaml
# Schema compains but cli complains with v2... ¯\_(ツ)_/¯
apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: defense-unicorns-testing
servers: 1
agents: 2
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer