name: Package and Test
run-name: ${{github.actor}} is running the package workflow
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'examples/after-deployment-validation-zarf/**'
      - 'utils/k3d/**'
  push:
    branches: [main]
    paths:
      - 'examples/after-deployment-validation-zarf/**'
      - 'utils/k3d/**'
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
permissions:
  contents: read
defaults:
  run:
    shell: bash
env:
  BRANCH_NAME: "${{ github.head_ref || github.ref_name }}"
  TAG: "${{ github.sha }}"
jobs:
  ##########
  # Zarf package build
  ##########
  package-podinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.26.1

      - name: Create Zarf Package
        working-directory: examples/after-deployment-validation-zarf
        run: |
          # build the zarf package
          zarf package create \
            --confirm \
            --skip-sbom

      - name: Create k3d Cluster
        run: |
          cd utils/k3d
          wget https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh
          bash -x install.sh
          rm -f install.sh
          k3d --version
          ./k3d_cluster.sh create

      - name: Zarf Init
        run: zarf init --confirm

      - name: Deploy Podinfo
        run: zarf package deploy zarf-package-after-deployment-validation-amd64.tar.gz --confirm

      - name: List installed packages
        run: zarf package list
